### ISSUE TITLE
Abstract out Name and Description

### ISSUE THREAD

**Issue by le0tan** [AY1920S1-CS2103T-W11-1/main#27]
... since `Name` and `Description` appear in both `Problem` and `Plan`, we should probably consider creating abstract classes for these two fields.

**Comment by tiuweehan** [comment]
I realize we currently can't do abstract classes for `Name` and `Description` as `isValidName` and `isValidDescription` are static classes...

**Comment by le0tan** [comment]
> I realize we currently can't do abstract classes for `Name` and `Description` as `isValidName` and `isValidDescription` are static classes...

Got it... guess the only way we have is to have multiple `Name` classes in separate packages? I removed it from v1.1 for now.

**Comment by tiuweehan** [comment]
I think we still have to refactor the `Name` and `Description` class eventually. If you look at the `ParserUtil` class, the method `parseName` returns a `Name` object referring to the field of a **Problem**. This means we cannot implement a separate `parseName` method that returns a `Name` object referring to the field of a **Plan**, since the the classes have the same name.
